otziv/main/urls.py
from django.urls import path
from . import views
app_name='main'

urlpatterns=[
    path('',views.main,name='main_list'),
    
]

otziv/otziv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls',namespace='main')),
    
    
]

otziv/main/models.py
from django.db import models
from django.contrib.auth import get_user_model

User=get_user_model()
class Post(models.Model):
    text=models.TextField()
    pub_date=models.DateField(auto_now_add=True)
    author=models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='posts')
class Uni(models.Model):
    Name=models.CharField(max_length=200)
    description=models.TextField(max_length=800)
    slug=models.SlugField(unique=True)

    def __str__(self):
        return self.text

otziv/main/views.py
from django.shortcuts import render

def main(request):
    return render(request,'main/main.html')

# Create your views here.

otziv/templates/includes/header.html
{% load static %}
...
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
<img src="{% static 'img/volk.png' %}">

otziv/templates/main/main.html
<!DOCTYPE html> 

<html lang="ru">
  <head>
    {% load static %}
    <link rel="stylesheet" href={% static "css/bootstrap.min.css" %}>
  </head>
  <body>
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">Активная</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">sd список</a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'main:main_list' %}">Действие</a></li>
          <li><a class="dropdown-item" href="#">Другое действие</a></li>
          <li><a class="dropdown-item" href="#">Что-то еще здесь</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="#">Отделенная ссылка</a></li>
        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Ссылка</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled">Отключенная</a>
      </li>
    </ul>
    
    <div class="row">
      <div class="col-sm-3">
        <div class="card" style="width: 18rem" >
          <img src="..." class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Заголовок карточки</h5>
            <p class="card-text">Небольшой пример текста, который должен основываться на названии карточки и составлять основную часть содержимого карты.</p>
            <a href="#" class="btn btn-primary">Перейти куда-нибудь</a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="card" style="width: 18rem" >
          <img src="..." class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Заголовок карточки</h5>
            <p class="card-text">Небольшой пример текста, который должен основываться на названии карточки и составлять основную часть содержимого карты.</p>
            <a href="#" class="btn btn-primary">Перейти куда-нибудь</a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="card" style="width: 18rem" >
          <img src="..." class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Заголовок карточки</h5>
            <p class="card-text">Небольшой пример текста, который должен основываться на названии карточки и составлять основную часть содержимого карты.</p>
            <a href="#" class="btn btn-primary">Перейти куда-нибудь</a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="card" style="width: 18rem" >
          <img src="..." class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Заголовок карточки</h5>
            <p class="card-text">Небольшой пример текста, который должен основываться на названии карточки и составлять основную часть содержимого карты.</p>
            <a href="#" class="btn btn-primary">Перейти куда-нибудь</a>
          </div>
        </div>
      </div>

    </div>
  </body> 
</html> 